４桁によるヒット＆ブローゲーム作成
daniel-software-tokyo/HitAndBlow pull request #3
Opened 2022-07-04 07:11 UTC by konta3291

4桁でのヒット＆ブローができました。
お忙しいところお手数だと思いますが、お手すきの際にでも評価のほどよろしくお願いします。

2022-07-04 23:17 UTC, nabemasamasa commented
PRのタイトルは一連の修正のお題目になりますね。
”Notification”、右上のベルマークで開ける画面で、IssueやPRの通知が一覧表示されるんですが、今「Pull request」になっちゃってて何の修正を行ったPRかわからなくなっちゃってます。
Editで後から修正も出来るので、修正お願いします。

2022-07-04 23:45 UTC, konta3291 commented
Editを使いタイトルを修正しました。ご確認よろしくお願いします。

2022-07-05 00:02 UTC, nabemasamasa requested changes
NG

2022-07-05 00:02 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlow.Test.vb
> +    <Test()> Public Sub ヒット4ブロー0の時()
[Q] 負の値を引数に取ったらどうなりますか？

2022-07-05 00:02 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +    Public Function DeleteHitNumber(Number As List(Of Char), hitIndexs As List(Of Integer)) As List(Of Char)
[Q] knowlegeのコーディングルールって読みました？

2022-07-05 00:02 UTC, nabemasamasa commented on HitAndBlow/Main.vb
[MUST] 出題者曰く、「意図する仕様と異ってます」ね……。

2022-07-05 00:02 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +                    If computerNumber(j) = playerNumber(k) Then
[Q] ユーザーが4桁以外入力した場合、どうなりますか？

2022-07-05 00:02 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Dim result As String = ("Hit:" & hit.ToString & "," & "Blow:" & blow.ToString)
「文字列補間式」で調べるとよりスッキリ書けそうです。

2022-07-05 00:02 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Dim computerNumber As New List(Of Char)(New Char() {"1"c, "2"c, "3"c, "4"c})
ここも、出題者の意図するところと違うはずです。

2022-07-05 00:02 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        hitIndexs.Reverse()
[nits] 私は、Reverseはここでやらせない方がいいと思います。
「数字が同じ場所を返す」に、"反転させて返す"罠が潜むことになってしまうからです。

2022-07-05 00:26 UTC, konta3291 commented on HitAndBlowTest/HitAndBlow.Test.vb
> +    <Test()> Public Sub ヒット4ブロー0の時()
[A] エラーになるようにしていないのです。
「-1234」なら処理はされますが、-も比較対象になります。
「-1-2-3-4」ではインデックス範囲を超えてしまいます。
0以上の整数しか受け取らないように修正します。

2022-07-05 00:29 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    Public Function DeleteHitNumber(Number As List(Of Char), hitIndexs As List(Of Integer)) As List(Of Char)
[A] 読みました。引数Numberが大文字開始であることについて話されていると思うので修正します。
他にありましたら教えて頂きたいです。

2022-07-05 00:41 UTC, konta3291 commented on HitAndBlow/Main.vb
#### 申し訳ありません。意図する仕様がわからないのですが教えて頂くことは可能でしょうか。
 - publicを使わないということでしょうか。
 - Sub Mainの中で処理を行い、別のファンクションで値を返すようにするということでしょうか。

2022-07-05 00:48 UTC, konta3291 commented on HitAndBlow/Main.vb
> +                    If computerNumber(j) = playerNumber(k) Then
[A]４桁以下の場合はインデックス範囲を超えてしまいます。
４桁以上だと処理はされますが、初めの４桁しか比較されず5桁目以降は無視されてしまいます。
４桁しか受け取らないように修正します。

2022-07-05 00:54 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Dim result As String = ("Hit:" & hit.ToString & "," & "Blow:" & blow.ToString)
ありがとうございます。
調べて取り入れます。

2022-07-05 01:02 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Dim computerNumber As New List(Of Char)(New Char() {"1"c, "2"c, "3"c, "4"c})
sub Mainで処理を行えばよろしいでしょうか。

2022-07-05 01:05 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        hitIndexs.Reverse()
ご指摘ありがとうございます。
修正します。

2022-07-05 04:22 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Dim computerNumber As New List(Of Char)(New Char() {"1"c, "2"c, "3"c, "4"c})
0～9の4桁の数字、なのに固定「1234」に見えるのですが…？

2022-07-05 04:31 UTC, nabemasamasa commented on HitAndBlow/Main.vb
本当はコードレビューと出題者は現実に即して、実装者と出題者(≒お客様)で切り離して、仕様に関する部分は別途会話にしたいんですが、、、、今日は現場なのでここで回答します。

「コンソールアプリケーションでユーザーが実際に4桁の数字を入力して、Hit&Blowが実行できるようにしてほしい」です。
今のままだと、Mainに何も定義してないので、実行してもすぐ閉じちゃいます。。。

2022-07-05 04:35 UTC, nabemasamasa commented
後、今気づいてしまってごめんなさいなんですが、これFork元の `daniel-software-tokyo`でPR立てちゃってますね……。

BaseブランチはFork先の konta3291 のmasterじゃないと、第一課題の要求仕様を満たしたのでmasterへマージ⇒第二課題の為最新masterからブランチはやして開発、のサイクルが回せないです。。。

GitHubの運用としてはForkして修正した内容を本流のPRに立ててマージしてもらう、だから初期設定がこうなってるんだろうけど、今はいらない……

2022-07-05 04:37 UTC, konta3291 commented on HitAndBlow/Main.vb
ご回答ありがとうございます。
わかりました、コンソールアプリケーションで動くようにします。

2022-07-05 04:38 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Dim computerNumber As New List(Of Char)(New Char() {"1"c, "2"c, "3"c, "4"c})
固定した数字でないとテストできないと思いまして固定していました。

2022-07-05 04:54 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +    Public Function DeleteHitNumber(Number As List(Of Char), hitIndexs As List(Of Integer)) As List(Of Char)
その通りです。今今他の違反は見つかってないですが、、、

大まかに意識しているルールは以下の通りです。

- 基本CamelCase
- 変数は他のクラスから参照できる(Public/Protected/Friend)ものは頭大文字、そうでなければ小文字
    - なので、メソッド引数はメソッド内でしか参照できないから頭小文字
- クラス名やプロパティ名は大文字始まり
- メソッド名は大文字始まりで動詞始まり
    - ただし一部例外あり
- Boolean型を返す変数/プロパティ/メソッドの命名は三単現動詞
    - これも一部例外あり
- 定数(Const, Shared ReadOnly)は`_`アンダースコア区切りの全部大文字

2022-07-05 06:35 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Dim computerNumber As New List(Of Char)(New Char() {"1"c, "2"c, "3"c, "4"c})
なるほど、だとしたらテスト対象のメソッドをランダムな数字を生み出す部分に影響しないようにして、テストできるようにするのはいかがでしょうか。

2022-07-05 07:48 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Dim computerNumber As New List(Of Char)(New Char() {"1"c, "2"c, "3"c, "4"c})
ご意見ありがとうございます。わかりました、修正します。

2022-07-05 07:50 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    Public Function DeleteHitNumber(Number As List(Of Char), hitIndexs As List(Of Integer)) As List(Of Char)
わかりました、注意して書くようにします。

2022-07-06 07:29 UTC, closed without merging

2022-07-06 07:29 UTC, Takatatsu9 commented
（watchしてなかったから立ってたこと自体に気付かんかった）

2022-07-06 07:33 UTC, nabemasamasa commented
(あぁ道理で当日通知が少ないと……納得)